-- FaeHub+ P1: operação escolar completa.
-- O Flask continua como única camada de acesso; a Data API permanece fechada.

create table public.account_roles (
  username text primary key references public.users(username) on delete cascade,
  role text not null check (role in ('responsavel','secretaria','coordenacao'))
);

create table public.guardian_links (
  id bigint generated by default as identity primary key,
  guardian_username text not null references public.users(username) on delete cascade,
  student_id text not null,
  relationship text not null,
  active boolean not null default true,
  unique (guardian_username,student_id)
);

create table public.period_closure_log (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.academic_periods(id),
  action text not null check (action in ('close','reopen')),
  actor text not null references public.users(username),
  reason text not null check (char_length(reason) between 5 and 500),
  created_at timestamptz not null default now()
);

create table public.class_diary_entries (
  id bigint generated by default as identity primary key,
  teacher text not null references public.users(username),
  class_name text not null,
  discipline text not null,
  lesson_date date not null,
  content text not null check (char_length(content) between 1 and 10000),
  objectives text not null check (char_length(objectives) between 1 and 5000),
  methodology text not null default '' check (char_length(methodology) <= 3000),
  resources text not null default '' check (char_length(resources) <= 2000),
  homework text not null default '' check (char_length(homework) <= 3000),
  observations text not null default '' check (char_length(observations) <= 5000),
  class_hours smallint not null default 2 check (class_hours between 1 and 12),
  status text not null default 'draft' check (status in ('draft','submitted','validated','returned')),
  coordinator_note text not null default '' check (char_length(coordinator_note) <= 3000),
  validated_by text references public.users(username),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.document_requests (
  id bigint generated by default as identity primary key,
  requester text not null references public.users(username),
  student_id text not null,
  document_type text not null check (document_type in ('matricula','frequencia','historico','ficha')),
  purpose text not null default '' check (char_length(purpose) <= 500),
  status text not null default 'requested' check (status in ('requested','processing','ready','delivered','rejected')),
  protocol text not null unique,
  verification_code text not null,
  note text not null default '' check (char_length(note) <= 1000),
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.pedagogical_interventions (
  id bigint generated by default as identity primary key,
  student_id text not null,
  opened_by text not null references public.users(username),
  category text not null check (char_length(category) between 1 and 80),
  summary text not null check (char_length(summary) between 5 and 1000),
  plan text not null check (char_length(plan) between 5 and 3000),
  status text not null default 'open' check (status in ('open','monitoring','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  recipient text references public.users(username),
  role_target text,
  title text not null check (char_length(title) between 1 and 160),
  body text not null check (char_length(body) between 1 and 2000),
  category text not null default 'sistema',
  action_url text not null default '' check (char_length(action_url) <= 500),
  created_by text references public.users(username),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  check (recipient is not null or role_target is not null)
);

create table public.notification_reads (
  notification_id bigint not null references public.notifications(id) on delete cascade,
  username text not null references public.users(username) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id,username)
);

create table public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  description text not null default '' check (char_length(description) <= 5000),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  event_type text not null check (event_type in ('evento','feriado','recesso','avaliacao','reuniao','conselho')),
  audience text not null default 'todos' check (audience in ('todos','aluno','professor','admin','responsavel','turma')),
  class_name text not null default '',
  location text not null default '' check (char_length(location) <= 160),
  created_by text not null references public.users(username),
  status text not null default 'published' check (status in ('published','cancelled')),
  created_at timestamptz not null default now(),
  check (ends_at >= starts_at),
  check (audience <> 'turma' or char_length(class_name) > 0)
);

create table public.password_recovery_requests (
  id bigint generated by default as identity primary key,
  username text not null references public.users(username),
  token_hash text,
  status text not null default 'requested' check (status in ('requested','issued','used','expired')),
  requested_at timestamptz not null default now(),
  expires_at timestamptz,
  issued_by text references public.users(username),
  used_at timestamptz
);

create table public.file_attachments (
  id bigint generated by default as identity primary key,
  owner text not null references public.users(username),
  entity_type text not null check (entity_type in ('message','exercise','submission')),
  entity_id bigint not null,
  filename text not null,
  mime_type text not null,
  size_bytes integer not null check (size_bytes between 1 and 5242880),
  content bytea not null,
  created_at timestamptz not null default now()
);

create index guardian_links_student_idx on public.guardian_links (student_id,active);
create index period_closure_log_period_idx on public.period_closure_log (period_id,created_at desc);
create index period_closure_log_actor_idx on public.period_closure_log (actor);
create index diary_teacher_date_idx on public.class_diary_entries (teacher,lesson_date desc);
create index diary_status_idx on public.class_diary_entries (status,lesson_date desc);
create index diary_validated_by_idx on public.class_diary_entries (validated_by);
create index document_requests_requester_idx on public.document_requests (requester,requested_at desc);
create index document_requests_student_idx on public.document_requests (student_id,status,requested_at desc);
create index interventions_opened_by_idx on public.pedagogical_interventions (opened_by);
create index interventions_student_idx on public.pedagogical_interventions (student_id,status,updated_at desc);
create index notifications_recipient_idx on public.notifications (recipient,created_at desc);
create index notifications_role_idx on public.notifications (role_target,created_at desc);
create index notifications_created_by_idx on public.notifications (created_by);
create index notification_reads_username_idx on public.notification_reads (username,read_at desc);
create index calendar_events_start_idx on public.calendar_events (starts_at,status);
create index calendar_events_created_by_idx on public.calendar_events (created_by);
create index password_recovery_status_idx on public.password_recovery_requests (status,requested_at desc);
create index password_recovery_username_idx on public.password_recovery_requests (username,requested_at desc);
create index password_recovery_issued_by_idx on public.password_recovery_requests (issued_by);
create index attachments_entity_idx on public.file_attachments (entity_type,entity_id);
create index attachments_owner_idx on public.file_attachments (owner,created_at desc);

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'account_roles','guardian_links','period_closure_log','class_diary_entries',
    'document_requests','pedagogical_interventions','notifications','notification_reads',
    'calendar_events','password_recovery_requests','file_attachments'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
  end loop;
end $$;

revoke all on all sequences in schema public from anon, authenticated;
