create table public.internships (
  id bigint generated by default as identity primary key,
  teacher text not null references public.users(username),
  company text not null check (char_length(company) between 1 and 120),
  title text not null check (char_length(title) between 1 and 160),
  description text not null check (char_length(description) between 1 and 10000),
  location text not null check (char_length(location) between 1 and 160),
  modality text not null check (modality in ('presencial', 'hibrido', 'remoto')),
  workload text not null default '' check (char_length(workload) <= 80),
  requirements text not null default '' check (char_length(requirements) <= 5000),
  application_url text check (
    application_url is null
    or (char_length(application_url) <= 2048 and application_url ~ '^https?://')
  ),
  application_instructions text not null default '' check (char_length(application_instructions) <= 3000),
  deadline date not null,
  class_name text not null default '3110',
  archived boolean not null default false,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  check (application_url is not null or char_length(application_instructions) > 0)
);

create index internships_teacher_idx
  on public.internships (teacher, archived, updated_at desc);

create index internships_class_deadline_idx
  on public.internships (class_name, archived, deadline);

alter table public.internships enable row level security;
revoke all on table public.internships from anon, authenticated;
revoke all on sequence public.internships_id_seq from anon, authenticated;
