-- Complete FaeHub+ messaging: groups, replies, edits, reactions and receipts.
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS group_id bigint;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS reply_to_id bigint REFERENCES public.messages(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS edited_at timestamptz;

CREATE TABLE IF NOT EXISTS public.message_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  class_name text,
  created_by text NOT NULL REFERENCES public.users(username),
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'messages_group_id_fkey'
  ) THEN
    ALTER TABLE public.messages ADD CONSTRAINT messages_group_id_fkey
      FOREIGN KEY (group_id) REFERENCES public.message_groups(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.message_group_members (
  group_id bigint NOT NULL REFERENCES public.message_groups(id) ON DELETE CASCADE,
  username text NOT NULL REFERENCES public.users(username) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, username)
);

CREATE TABLE IF NOT EXISTS public.message_receipts (
  message_id bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  username text NOT NULL REFERENCES public.users(username) ON DELETE CASCADE,
  delivered_at timestamptz,
  read_at timestamptz,
  PRIMARY KEY (message_id, username),
  CHECK (read_at IS NULL OR delivered_at IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS public.message_reactions (
  message_id bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  username text NOT NULL REFERENCES public.users(username) ON DELETE CASCADE,
  emoji text NOT NULL CHECK (emoji IN ('👍','❤️','😂','😮','👏','✅')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, username, emoji)
);

CREATE INDEX IF NOT EXISTS messages_direct_thread_idx
  ON public.messages(sender, recipient, id DESC) WHERE group_id IS NULL;
CREATE INDEX IF NOT EXISTS messages_group_thread_idx
  ON public.messages(group_id, id DESC) WHERE group_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS message_group_members_user_idx
  ON public.message_group_members(username, group_id);
CREATE INDEX IF NOT EXISTS message_receipts_user_idx
  ON public.message_receipts(username, read_at, message_id);
CREATE INDEX IF NOT EXISTS message_reactions_message_idx
  ON public.message_reactions(message_id);

INSERT INTO public.message_groups(name, class_name, created_by)
SELECT 'Turma 3110', '3110', 'aline'
WHERE EXISTS (SELECT 1 FROM public.users WHERE username='aline')
  AND NOT EXISTS (SELECT 1 FROM public.message_groups WHERE class_name='3110');

INSERT INTO public.message_group_members(group_id, username)
SELECT g.id, u.username
FROM public.message_groups g
JOIN public.users u ON u.username IN (
  'aline','gilberto','thiago.zotti','jonathan.samuel','pablo.sousa','marlon.eduardo'
)
WHERE g.class_name='3110'
ON CONFLICT DO NOTHING;

INSERT INTO public.message_receipts(message_id, username, delivered_at, read_at)
SELECT id, recipient,
       CASE WHEN is_read THEN created_at END,
       CASE WHEN is_read THEN created_at END
FROM public.messages
WHERE group_id IS NULL
ON CONFLICT DO NOTHING;

COMMENT ON TABLE public.message_receipts IS
  'Per-user delivery and read state for direct and group messages.';
